// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Chimayo.Ssis.Xml")>]
[<assembly: AssemblyProductAttribute("Chimayo.Ssis")>]
[<assembly: AssemblyDescriptionAttribute("Chimayo is a library for creating and manipulating SQL Server Integration Services packages with F# code.")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Chimayo.Ssis.Xml"
    let [<Literal>] AssemblyProduct = "Chimayo.Ssis"
    let [<Literal>] AssemblyDescription = "Chimayo is a library for creating and manipulating SQL Server Integration Services packages with F# code."
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
